spring.application.name=Semana3Repartido1

spring.datasource.url=jdbc:postgresql://${DATABASE_URL}:${PGPORT}/${POSTGRES_DB}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true